import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Typography } from '@mui/material'
import { useRouter } from 'next/router'
import { useEffect } from 'react'

import data from '../config'

import Timer from '../components/Timer'

export default function Home() {
  const router = useRouter() 

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant="h1" className={styles.title} sx={{ fontWeight: 'bold' }}>
          Days until Katie
        </Typography>

        <Timer />
      </main>

      <footer className={styles.footer}>  
        Powered by{" "}
        <Typography inline sx={{ display: "inline-block", whiteSpace: "pre", color: 'blue', fontWeight: 'bold' }}>
         {' Because();'}
        </Typography>
      </footer>
    </div>
  )
}
